version: "3"
services:
  db: 
    image: "postgres"
    environment:
      POSTGRES_DB: service
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
